# -*- coding: utf-8 -*-
"""AI - Lab 6 - Naive Bayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dmWJHIt_uHCUnL4q5xxWlUlWDcB33A_l
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pandas

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv', header=None)
df = pd.DataFrame(df)
df.columns = ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"]
df

df.describe()

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import accuracy_score
print('accuracy is',accuracy_score(y_pred,y_test)*100,"%")

df = pd.DataFrame({'Real Species':y_test, 'Predicted Species':y_pred})
df