# -*- coding: utf-8 -*-
"""AI - Lab 7 - Logistic Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LUMvrgPBFOPj9eNmf88tHOj9RmzePm1G
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pandas

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv', header=None)
df = pd.DataFrame(df)
df.columns = ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"]
df

df.describe()

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

X = df.drop(columns = ['species'])
Y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
#probs_y= model.predict_proba(X_test)


print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import accuracy_score
print('accuracy is',accuracy_score(y_pred,y_test)*100, )

df = pd.DataFrame({'Real Species':y_test, 'Predicted Species':y_pred})
df